### ISSUE TITLE
Unable to change the from_email

### ISSUE THREAD

**Issue by KanwalPrakashSingh** [akhoury/nodebb-plugin-emailer-mandrill#11]
How do I change the from_email ? 

I'm unable to send the mail using my own domain, everything gets sent via some random domain (say no-reply@xyz.com)

**Comment by rudimk** [comment]
I seem to be facing this issue too. Any pointers, @akhoury?

**Comment by rudimk** [comment]
Okay, so a quick fix is to modify the ```index.js``` file in ```<your nodebb installation>/node_modules/nodebb-plugin-emailer-mandrill``` and manually set the ```from_email``` here:

```javascript
mandrill('/messages/send', {
            message: {
                to: [{email: data.to, name: data.toName}],
                subject: data.subject,
                from_email: '',
                from_name: '',
                html: data.html,
                text: data.plaintext,
                auto_text: !!!data.plaintext,
                headers: headers
            }
        }, function (err, response) {
            if (!err) {
                winston.verbose('[emailer.mandrill] Sent `' + data.template + '` email to uid ' + data.uid);
            } else {
                winston.warn('[emailer.mandrill] Unable to send `' + data.template + '` email to uid ' + data.uid + '!!');
                winston.warn('[emailer.mandrill] Error Stringified:' + JSON.stringify(err));
            }
        });
```

It's not elegant, and chances are that a plugin update might overwrite these changes, but it works for now.

**Comment by KanwalSingh** [comment]
@rudimk actually <forum_url>/admin/settings/email
I set a from address via this. it works !
