### ISSUE TITLE
Implement error condition: "Bounce a return back to sender"

### ISSUE THREAD

**Issue by djensen47** [akhoury/nodebb-plugin-emailer-mandrill#18]
It looks like there is a TODO that is not explicitly called out but the code doesn't do what the comment says:

```
// Bounce a return back to sender
```

https://github.com/akhoury/nodebb-plugin-emailer-mandrill/blob/master/index.js#L231

**Comment by julianlam** [comment]
:laughing: Well, let's have it do something now...

**Comment by julianlam** [comment]
v0.3.4
