### ISSUE TITLE
Reply by mail not working

### ISSUE THREAD

**Issue by sebastien49** [akhoury/nodebb-plugin-emailer-mandrill#26]
First, I'm french so sorry for my english :)

Second, I can not make the reply by mail work.

When I run the logs (./nodebb log) I see that the test mails sent from mandrill directly arrive at home ([emailer.mandrill.verifyEvent] Could not locate post id)

I receive notifications of new messages and when I reply to the mail (reply-*@inbound.mydomain.fr) nothing happens ....

Can you help me?

I specify in advance that I am not a developer.

My configuration is:

Hosting at OVH via VPS
Ubuntu 16.04

Thank you in advance :)

**Comment by psychobunny** [comment]
fixed in latest version of nodebb (1.8.0, coming soon)
or latest master as of this commit: https://github.com/NodeBB/NodeBB/commit/9e0189ab34d6ef4e6348dad1562d9c3299fd5617
